# Id de tag
remote_tag_id: 0x6833

#Id de anchor
anchor1_id: 0x6866
anchor2_id: 0x6865
anchor3_id: 0x6831
anchor4_id: 0x6854

#Posicion de los anchor en mm (referencias)
anchor1_x: 4550
anchor1_y: 0
anchor1_z: 2100

anchor2_x: 0
anchor2_y: 0
anchor2_z: 2300

anchor3_x: 4550
anchor3_y: 2980
anchor3_z: 2400

anchor4_x: 0
anchor4_y: 3020
anchor4_z: 1600
